name: innoscripta_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl:
  sqflite_common_ffi:
  flutter_bloc:
  bloc: 
  equatable: 
  path: 
  collection:
  sqflite: 
  font_awesome_flutter: 
  flutter_slidable: 
  about: 
  url_launcher: 
  flutter_svg: 
  flutter_material_color_picker: 
  flutter_datetime_picker: 
  csv: 
  path_provider: 
  share_plus: 
  cross_file: 
  shared_preferences: 
  fl_chart: 
  card_swiper: 
  flutter_typeahead: 
  flutter_app_badger: 
  numberpicker: 
  file_picker: 
  flutter_local_notifications: 
  flutter_markdown: 
  package_info_plus: 
  xdg_directories: 
  fluent: 
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  effective_dart: ^1.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_driver:
    sdk: flutter
  test: ^1.17.10
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - README.md
    - l10n/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
